// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Post struct {
	ID        uuid.UUID     `json:"id"`
	Index     sql.NullInt32 `json:"index"`
	PostName  string        `json:"post_name"`
	PostData  string        `json:"post_data"`
	Tags      []string      `json:"tags"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}
